################################################
###                                          ###
###          • ADNAP MINI GAMES •            ###
###          www.adnapstudios.com            ###
###                                          ###
###        ~  CONFIGURATION FILE  ~          ###
###                                          ###
################################################

# Plugin created by MarnikM

## Global Configuration ##

shop-config-url: https://raw.githubusercontent.com/Adnap-Studios/config-files/main/adnap-mini-games/v1.0/shop.yml
database:
  host: localhost
  port: 3306 # Default MySQL/MariaDB 5 port
  database-name: minigames
  username: username
  password: password


