################################################
###                                          ###
###          • ADNAP MINI GAMES •            ###
###          www.adnapstudios.com            ###
###                                          ###
###        ~  CONFIGURATION FILE  ~          ###
###                                          ###
################################################

# Plugin created by MarnikM

## Global Configuration ##




