name: AdnapMiniGames
version: 1.0
author: MarnikM
main: com.adnapstudios.adnapminigames.AdnapMiniGames
api-version: 1.17
commands:
  shop:
    description: Opens a shop
  shopkeeper:
    description: Gives a Shopkeeper Spawn Egg
  removeshopkeeper:
    description: Removes the nearby shopkeeper
  pos1:
    description: Sets pos1
  pos2:
    description: Sets pos2
  arena:
    description: Arena configuration
  amgspawn:
    description: Spawnpoint configuration